apiVersion: v1
kind: Pod
metadata:
  name: todo
spec:
  containers:
    - name: todo-app
      image: divyanshukumarsingh/next_todo:fc7981f1560a23d9328aabcce4cb36c5cbe8e886
      ports:
        - containerPort: 80
