apiVersion: v1
kind: Pod
metadata:
  name: todo
spec:
  containers:
    - name: todo-app
       divyanshukumarsingh/next_todo:df697d3ccbe73e66bbfa3e5cb4051b57c17391fcfc7981f1560a23d9328aabcce4cb36c5cbe8e886
      ports:
        - containerPort: 80
